language: python
python:
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
before_install:
    - sudo apt-get update
    - sudo apt-get -y install mcl
    - sudo apt-get -y install mafft
    - sudo apt-get -y install fasttree
    - wget http://github.com/bbuchfink/diamond/releases/download/v2.0.5/diamond-linux64.tar.gz 
    - tar -xzf diamond-linux64.tar.gz
    - export PATH=$PATH:$PWD/
    - wget http://abacus.gene.ucl.ac.uk/software/paml4.9j.tgz
    - tar -xzf paml4.9j.tgz
    - pushd paml4.9j/src && make -f Makefile && popd 
    - export PATH=$PATH:$PWD/paml4.9j/src/
install:
    - pip install -r requirements.txt
    - pip install .
script: pytest
